version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - UPSTREAM_URL=https://assignment-server-rv-866595813231.us-central1.run.app/
      - UPSTREAM_USERNAME=tomer.adar
      - UPSTREAM_PASSWORD=chip2255
      - POLLING_INTERVAL=5
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:////workspace/data/microscopy.db
    volumes:
      - ./data:/workspace/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - "9999:8080"
    environment:
      - DOZZLE_PORT=8888
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

